version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres
    env_file:
      - dev.env
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - dev.env
    restart: on-failure
    volumes:
      - redis_data:/data
  app:
    build: .
#    command: python appapp.py
    command: bash "run_dev.sh"
    env_file:
      - dev.env
    restart: always
    ports:
      - "5556:5555"
      - "8020:8015"
    depends_on:
      - redis
    volumes:
      - .:/app

  frontend:
    container_name: vue_app
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    env_file:
      - dev.env

volumes:
  redis_data:
  db:
