"""added created_by_id_to_transactions_new

Revision ID: 9609402b18c7
Revises: 449046640ab2
Create Date: 2024-10-14 18:09:05.437769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9609402b18c7'
down_revision: Union[str, None] = '449046640ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'transactions', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'created_by_id')
    # ### end Alembic commands ###
